# users-prod.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod-users-service  # Replace localhost with production database host
    username: ${DB_USERNAME}  # Database username from environment variable
    password: ${DB_PASSWORD}  # Database password from environment variable
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000       # 30 seconds
      max-lifetime: 1800000     # 30 minutes
      connection-timeout: 30000 # 30 seconds

  jpa:
    hibernate:
      ddl-auto: none             # Prevents accidental schema modifications
    show-sql: false              # Disable SQL logging in production
    properties:
      hibernate:
        format_sql: false

  config:
    import: "optional:configserver:http://localhost:8071/"  # Replace localhost with the actual hostname or IP

security:
  jwt:
    secret: ${JWT_SECRET_KEY}     # JWT secret from environment or secret manager
    expiration: 2h                # Token expiration (2 hours)

logging:
  level:
    root: INFO                    # General logging level
    com.galvatron.users: WARN   # Service-specific logging (adjust as needed)

management:
  endpoints:
    web:
      exposure:
        include: health, info     # Expose only critical management endpoints

# Production-specific application properties
app:
  max-login-attempts: 5           # Maximum allowed login attempts
  session:
    timeout: 30m                  # Session timeout (30 minutes)
